### ISSUE TITLE
default_connection type not propagated to gateways connections

### ISSUE THREAD

**Issue by martinburch** [SQLMesh/sqlmesh#4105]
I have several gateways defined in `config.yaml` which are all using the same connection type.

```
gateways:
  local:
    connection:
      type: mssql
      host: localhost
      user: placeholder
      database: local
  staging:
    connection:
      type: mssql
      host: staging.server
      user: placeholder
      database: staging
```

Why can't I specify
```
default_connection:
  type: mssql
```
And have `type: mssql` propagate to the local and staging connections?

When I try to remove the `type: mssql` definitions from the gateway connections after defining `type: mssql` in default_connection, I get `Error: Missing connection type.` when running `sqlmesh --gateway staging info` This behaviour seems contrary to the docs: https://sqlmesh.readthedocs.io/en/stable/guides/configuration/#default-connectionsscheduler
> The default_connection, default_test_connection, and default_scheduler keys are used to specify shared defaults across multiple gateways.
